version: '3.8'

services:
    mysql:
        image: 'mysql:8.0'
        container_name: 'crawlofgencraft_db'
        environment:
            MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
            MYSQL_DATABASE: "crawlofgencraft"
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data: {}
