services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crawlofgencraft_app
    volumes:
      - .:/var/www/html
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=crawlofgencraft
      - DB_USERNAME=root
      - DB_PASSWORD=

  mysql:
    image: 'mysql:8.0'
    container_name: 'crawlofgencraft_db'
    environment:
        MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
        MYSQL_DATABASE: "crawlofgencraft"
    ports:
        - "3306:3306"
    volumes:
        - db_data:/var/lib/mysql

volumes:
    db_data: {}