name: crawlofgencraft
version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: crawlofgencraft_app
    volumes:
      - ../:/var/www/html:cached
      - /var/www/html/vendor
      - /var/www/html/node_modules
    ports:
      - "9000:9000"
    depends_on:
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_DATABASE=crawlofgencraft
      - DB_USERNAME=root
      - DB_PASSWORD=root

  mysql:
    image: 'mysql:8.0'
    container_name: 'crawlofgencraft_db'
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "crawlofgencraft"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  nginx:
    image: nginx:latest
    container_name: 'crawlofgencraft_nginx'
    ports:
      - "8000:80"
    volumes:
      - ../:/var/www/html:cached
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

volumes:
  db_data: {}
