name: Code Quality

on: [push, pull_request]

jobs:
  quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          composer install
          npm install
          
      - name: Run PHP linting
        run: |
          ./vendor/bin/pint --test
          ./vendor/bin/phpcs
          
      - name: Run JS/Vue linting
        run: |
          npm run lint